feature: my recruits detail page
5-PS/The-Julge pull request #33
Opened 2024-04-18 14:25 UTC by juniorcoma

## 🚀 작업 내용

- [x] 내 공고 상세 페이지 목업 디자인 입니다.

## 📝 참고 사항

- 공고 내용은 따로 컴포넌트로 빼줬습니다.

## 🖼️ 스크린샷
![스크린샷 2024-04-18 231435](https://github.com/5-PS/The-Julge/assets/143431179/f51b1ffa-a128-4252-beb9-1b5ca730716f)
![스크린샷 2024-04-18 231440](https://github.com/5-PS/The-Julge/assets/143431179/9f73f5b8-c088-46ec-8203-bd2b7735f2f2)
![스크린샷 2024-04-18 231504](https://github.com/5-PS/The-Julge/assets/143431179/f5a6c255-39af-42e7-91ea-da1b4f1f811e)
![스크린샷 2024-04-18 231509](https://github.com/5-PS/The-Julge/assets/143431179/19c7c82e-5ba0-4d48-9d5a-213aefa01417)
![스크린샷 2024-04-18 231521](https://github.com/5-PS/The-Julge/assets/143431179/c59d7b14-0473-4473-9446-6f5aba081fc2)
![스크린샷 2024-04-18 231526](https://github.com/5-PS/The-Julge/assets/143431179/1b6a698e-64d4-40f8-acbd-9243370752fb)

## ✅ 이후 계획

- 공고 내용은 따로 빼서 그안에서  api를 불러와 데이터를 조립해서 이 컴포넌트에만 스켈레톤 UI 적용시킬 예정입니다.
-

2024-04-19 04:37 UTC, hsmurf approved these changes
시급 비교 라벨은 제가 따로 빼놓을게요!

2024-04-19 04:37 UTC, hsmurf commented on components/pagination/pagination.tsx
```
py-[8px] px-[12px] -> py-2 px-3
gap-[4px] md:gap-[2px] -> gap-1 md:gap-0.5
w-[24px] h-[24px] p-[12px] md:w-[40px] md:h-[40px] -> w-6 h-6 p-3 md:w-10 md:h-10
``` 
P4: 있는 단위라서 바꾸면 좋을거 같아요

2024-04-19 05:53 UTC, NJ97S requested changes
수고하셨습니다 🫡🫡🫡

2024-04-19 05:53 UTC, NJ97S commented on app/(service)/my-store/my-recruits/[recruitId]/_components/recruitsCard.tsx
> +          </Button>
P1: `height` 속성 지정이 필요합니다.

2024-04-19 05:53 UTC, NJ97S commented on app/(service)/my-store/my-recruits/[recruitId]/_components/recruitsCard.tsx
> +              </span>
P2: 글자가 아래로 치우쳐져 있는 것 같아, 가운데 정렬이 필요할 것 같습니당

2024-04-19 05:53 UTC, NJ97S commented on app/(service)/my-store/my-recruits/[recruitId]/page.tsx
> +function MyRecruitDetailPage({ searchParams }) {
P2: `searchParams`가 `any` 타입이라 타입 지정이 필요할 것 같습니다.

2024-04-20 04:45 UTC, ChoiMHMH approved these changes
_components에 사용될 컴포넌트 각각 모아두니 좋은 것 같습니당
수고하셨습니다!

2024-04-22 08:08 UTC, Young2un approved these changes
수고하셨습니다~!

2024-04-22 16:36 UTC, NJ97S approved these changes
수고하셨습니다 👍👍👍

2024-04-22 16:36 UTC, merged